### ISSUE TITLE
New feature to show types doesn't work on windows

### ISSUE THREAD

**Issue by archaeron** [carymrobbins/intellij-haskforce#113]
I've seen the new feature from #90 work on linux and it's perfect.
On windows though I get:
> ghc-modi error
> ghc-modi execution was aborted: java.util.concurrent.ExecutionException:
> java.lang.NoClassDefFoundError: com/haskforce/utils/SystemUti

tested on two machines with ghc-mod 5.1.1.0 and 5.2.1.2

**Comment by KasperJanssens** [comment]
Weird, because I don't use the SystemUtil in GhcModi (I actually should have, didn't know this existed) : https://github.com/carymrobbins/intellij-haskforce/blob/cee8c2c8be9112652965b1f63ab714e1d066b080/src/com/haskforce/highlighting/annotation/external/GhcUtil.java

I seem to have run out of windows some time ago, can't really reproduce, so I'm going to start guessing. It makes me think of a jvm issue. NoClassDefFound only one one platform is really weird unless the jvm installed on that platform doesn't support some stuff that is imported in SystemUtil.

**Comment by archaeron** [comment]
Is there a log that I can paste here that helps find the error?

**Comment by KasperJanssens** [comment]
Don't think so, but start with the output of  'java -version' on that machine.

**Comment by carymrobbins** [comment]
I have tried this on Windows 7 and it works well.  Here are the specs from **Help > About** -

```
IntelliJ IDEA 14.0.2
Build #IC-139.659
JRE: 1.6.0_45-b06 amd64
```

What's weird about this issue is that the class file **SystemUtil** is built into the jar, so it's not clear why your JVM is not able to find it.  It's particularly strange that this is happening on two different machines.  I'd be interested to see if uninstalling and reinstalling the plugin helps.

@archaeron - What versions of Windows, IntelliJ, and Java are you running?

**Comment by archaeron** [comment]
Hello

sorry, I had to reinstall my System and had no time for trying this out again.
I can confirm that it's working now for me. 
Thank you
