### ISSUE TITLE
Comments `add · remove /= id`

### ISSUE THREAD

**Issue by tolysz** [carymrobbins/intellij-haskforce#116]
adding/removing comments with `ctrl + / ` changes indentation (moves from 1 space out to zero)
eg for:

    data YoutubeChannel = YoutubeChannel
     { _ycKind                :: ApiKind "youtube#channel" 
     , _ycEtag                :: Text
     , _ycId                  :: Text
     }

**Comment by carymrobbins** [comment]
Looks like this is an issue in IntelliJ.  The uncomment action attempts to be smart and remove a single space between the comment prefix and the commented code.  However, this breaks down for us since our comment prefix is `"-- "` with a trailing space.  Without the trailing space we'd end up creating code that doesn't parse in other places since `--?` is a valid operator, where `?` is any valid operator.

I have reported issue [IDEA-135341](https://youtrack.jetbrains.com/issue/IDEA-135341) and submitted pull request https://github.com/JetBrains/intellij-community/pull/235 to address this.

**Comment by carymrobbins** [comment]
This should be resolved in the latest builds of IntelliJ.
