### ISSUE TITLE
Run problems

### ISSUE THREAD

**Issue by JohnReedLOL** [carymrobbins/intellij-haskforce#240]
See: 

http://stackoverflow.com/questions/35259912/how-to-get-haskell-documentation-to-appear-in-intellij

Note that it needs to be more obvious that the first thing the user needs to do after installing Haskforce is "Run > Run Configuration > "+" > Cabal Run > Name it "CabalRun" > Ok" and then click the green Run arrow. Like that's the second most important thing just after "Uninstall IntelliJ Haskell Plugin". 

Also, it is traditional for a new project to contain a "Main" module with a "main" function that prints "Hello World" so that when the user actually clicks the green arrow, they see "Hello World" and know that everything is working.

**Comment by carymrobbins** [comment]
@JohnReedLOL - It looks like this is a cabal dependency issue, which I've updated in the comments of that SO question.

**Comment by JohnReedLOL** [comment]
Ok. Fixed that cabal dependency issue. Now auto-complete doesn't work. "Ctr-B" works to jump to a function declaration in the same project, but Ctr-Space doesn't work and clicking "Code > Haskell Completion Cache Reload" didn't fix the problem.

**Comment by carymrobbins** [comment]
@JohnReedLOL - I'd check to make sure ghc-mod is running.  Look in the IntelliJ event log and ensure you don't have any error messages.  If not, open a Haskell file in your project, then go to **Tools > Restart ghc-modi**.  You can also double check the processes directly by doing -

```
$ ps aux | grep ghc-mod
``` 

If that doesn't work I'd check the [IntelliJ logs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) and report any relevant stack traces you see.  You can also try restarting the IDE to see if that gives it a chance to sync back up, although ideally that shouldn't be necessary.

I noticed from your SO screenshots that you are using a pretty old version of GHC.  I'd recommend using [Stack](http://docs.haskellstack.org/en/stable/README.html) instead of cabal as it manages your  GHC installation and dependencies very nicely.  The `lts-5.0` resolver gets you GHC 7.10.3, which is pretty current.

**Comment by carymrobbins** [comment]
@JohnReedLOL - Are you still experiencing this issue?
