### ISSUE TITLE
"Could not find GHC version in ghc-mod version info:"

### ISSUE THREAD

**Issue by chris-martin** [carymrobbins/intellij-haskforce#241]
I set up a Stack project, configured the path to `ghc-modi`, and got this error message in the event log:

> Could not find GHC version in ghc-mod version info:

I can't work out what it means.

**Comment by chris-martin** [comment]
I have a lot of other questions, possibly related to this issue. Does there need to be a Haskell "SDK" configured (if so, what does it need to point to)? What behavior can I expect to see if I ever get this working? Will the editor show compile errors?

**Comment by carymrobbins** [comment]
A couple of questions to understand your configuration -

1. What are the paths and flags you have configured for ghc-mod and ghc-modi?  Does the settings GUI display their versions?  If so, what are they?
1. What is the output of running `stack ghc -- --version` ? (from your project root).
1. What is the output of running `stack exec -- path/to/ghc-mod --version` ? (explicitly using your configured ghc-mod path)

> Does there need to be a Haskell "SDK" configured (if so, what does it need to point to)?

Yes, parts of IntelliJ depend on the SDK's existence, but not on its path.  I currently have it configured with an arbitrary path to get around the features which require the SDK to exist.  Ideally, we shouldn't need one, but I haven't found a way around it.

> What behavior can I expect to see if I ever get this working? Will the editor show compile errors?

Yes, you should see compilation errors, usually reported from ghc-mod.  You can experiment with this by running `stack exec -- path/to/ghc-mod check <file.hs>`

**Comment by carymrobbins** [comment]
Also, to explain the error you saw -

> Could not find GHC version in ghc-mod version info:

This is validating your configured ghc-mod version, ensuring that it was compiled against the same version of GHC that you are using (otherwise, you get weird issues).  It seems it didn't get any output from checking the ghc-mod version, so we need to figure out why that is.

**Comment by chris-martin** [comment]
In the GUI:

> GHC Mod 
> * Path: /run/current-system/sw/bin/ghc-mod
> * Version: ghc-mod version 5.4.0.0 compiled by GHC 7.10.2
>
> GHC Modi
> * Path: /run/current-system/sw/bin/ghc-mod
> * Version: ghc-mod version 5.4.0.0 compiled by GHC 7.10.2

I'm not sure why the Modi path is set to `ghc-mod` rather than `ghc-modi`. When I try to change it to `modi`, it automatically changes back to `mod` next time I open the settings.

```
> stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

```
> stack exec -- /run/current-system/sw/bin/ghc-mod --version
ghc-mod version 5.4.0.0 compiled by GHC 7.10.2
```

```
> stack exec -- /run/current-system/sw/bin/ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

**Comment by carymrobbins** [comment]
> I'm not sure why the Modi path is set to ghc-mod rather than ghc-modi. When I try to change it to modi, it automatically changes back to mod next time I open the settings.

This is because `ghc-modi` is actually "deprecated".  In its place we pass the `legacy-interactive` flag, which you will probably notice in the **Flags** field.  Do you have any other flags specified in your settings?  Also, does the `stack` executable you are calling on the command line (`which stack`) match the one you have configured in HaskForce?  You can find the configuration in -

**File > Settings > Build, Execution, Deployment > Compiler > Haskell Compiler > Stack path**

This should have been done when originally creating the project.

Feel free to jump on **#haskforce** on freenode if you'd like to troubleshoot the issue in real-time.  Ping me via my handle, **crobbins**.

**Comment by carymrobbins** [comment]
@chris-martin - I'm cleaning up some things so we'll get better errors in the IDE when exec processes fail.  This will be included in the next release, which will hopefully be out either tonight or tomorrow.

**Comment by carymrobbins** [comment]
@chris-martin - The release is out and published to Jetbrains' plugin repo, so **Help > Check for Update** should prompt to install the latest version.  Included is the improved error reporting as promised, as well as some clean up to the ghc-mod and error checking implementation, so post back if you are still experiencing the issue.

**Comment by chris-martin** [comment]
That fixed it! Thanks a ton.

**Comment by carymrobbins** [comment]
Awesome, thanks @chris-martin, this really helped clean up some stuff.
