### ISSUE TITLE
GHC-Mod/GHC-Modi/Stack mess/hell

### ISSUE THREAD

**Issue by OmanF** [carymrobbins/intellij-haskforce#247]
I'm not sure how to even describe the issue I'm facing.
Basically, I start Intellij on a newly minted Haskell project (which I started by "cabal init" in the folder the source files are contained in) and I get the errors you see in the screenshot.
(Included are screenshots of the plugin settings and the relevant portion of the .zshrc file).  
(As can be seen, Haskell 7.10.3 compiled from source, Cabal 1.22.7.0 and Cabal-install 1.22.8.0 compiled from source, Stack 1.0.2 compiled from source. All applications **are** placed where the .zshrc file points to).  
If there's anymore info needed to handle this issue, let me know and I'll do my best to provide it.  
Thanks.  

![ghcmodissue](https://cloud.githubusercontent.com/assets/7848797/13318724/1c3b886a-dbc5-11e5-9e84-72f48c8ec154.png)
![settings](https://cloud.githubusercontent.com/assets/7848797/13318732/21c9731e-dbc5-11e5-93eb-370c7e0502fa.png)
![zshrc](https://cloud.githubusercontent.com/assets/7848797/13318733/24c01bfe-dbc5-11e5-9aec-8bb948d02fb6.png)

**Comment by OmanF** [comment]
P.S. As can be seen in the attached screenshot... no Tools -> Restart ghc-modi  
  
![norestart](https://cloud.githubusercontent.com/assets/7848797/13319072/b5ec7058-dbc7-11e5-90b3-7e14a726fb9d.png)

**Comment by carymrobbins** [comment]
@OmanF - It seems you are trying to mix cabal and stack in the same project, which won't work.  Since you are starting with a new project, use the IntelliJ new project wizard and choose Stack as your builder, as described in the [Quick Start Guide](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#creating-a-new-project).  This will take care of initializing and configuring the project for you.

**Comment by OmanF** [comment]
Yes, thank you! Fixed.
Also, should mention the Settings->Build, Execution, Deployment->Compiler->Haskell compiler and change the build mechanism there or it will still cause issue.

Closing it.
Thanks.
