### ISSUE TITLE
Stylish-haskell always saying "code is already properly formatted".

### ISSUE THREAD

**Issue by davips** [carymrobbins/intellij-haskforce#303]
Intellij 2016.1.4
Haskforce 0.3-beta.36
Stylish-haskell 0.6.4.0 [correctly found by haskforce detection]

Example:
gravity =9.8:: Float

If the line is selected, it fails silently; if nothing is selected, it reports "code is already properly formatted".

Thanks for this great project, this is the only "IDE" with all my Haskell (beginner) needs.
(tried atom, emacs and leksah)

**Comment by davips** [comment]
Ok, I found that Haskforce adds two extra shortcuts, besides the original: ctr+alt+e and ctrl+alt+d.
Is that documented somewhere? Am I missing something, or the Intellij's list of shortcuts is, for now, the place to discover the functionalities of Haskforce?

**Comment by carymrobbins** [comment]
> Is that documented somewhere?

@davips - In the wiki there's a [Keyboard Shortcuts](https://github.com/carymrobbins/intellij-haskforce/wiki/Keyboard-Shortcuts) section.

> If the line is selected, it fails silently; if nothing is selected, it reports "code is already properly formatted".

Maybe this could be improved, as that sounds confusing.  Since we don't have a "native" IntelliJ formatter and defer to external tools like stylish and hindent, there might be a way to have the dialog respond with some warning and to suggest using one of the aforementioned tools.
