### ISSUE TITLE
False alert

### ISSUE THREAD

**Issue by kindlychung** [carymrobbins/intellij-haskforce#314]
```haskell
x :: Char
x = 'h'

tell :: (Show a) => [a] -> String
tell []      = "The list is empty"
tell [x]     = "The list has one elem: " ++ show x  -- x shadowing x
tell [x, y]  = "The list has two elems: " ++ show x ++ show y
tell (x:y:_) = "The list is long, first two elems are: " ++ show x ++ show y
```

I got an error in intellij that says x shadowed an existing binding. The program compiled ok. Is this a feature? How do you avoid this error?

**Comment by NobbZ** [comment]
It is not an error but a warning and you should get it from GHC as well
when using `-Wall` flag.

It tells you that your x bound by the pattern match shadows the x from the
top level function definition.

Easiest way to get rid of the warning is to disable it, but the only true
way of getting rid of it is to rename one of the bindings in question.
Usually it should be the local binding, because renaming something at the
top level might introduce changes in unrelated modules or even your
dependent projects.

Kaiyin Zhong <notifications@github.com> schrieb am Mo., 26. Dez. 2016,
21:29:

**Comment by carymrobbins** [comment]
Thanks @NobbZ for fielding this one!
